### ISSUE TITLE
Renault API has stopped working! Change required.

### ISSUE THREAD

**Issue by Dave-09** [MattCheetham/zeddy-support#11] opened 2020-07-01 18:22 UTC
Hello Matt,

The Kameron token was removed from requests. Can you make a fix for Zeddy?

Thank you!

**Comment by MattCheetham** [comment] 2020-07-01 19:13
Duplicate of #10. Please make sure to check recently closed and pinned issues before posting.

**Closed** 2020-07-01 19:13 UTC
Labels: bug, duplicate

**Comment by Dave-09** [comment] 2020-07-01 20:15
Excuses! I had not looked at the FIXED option.
